# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Polaris  
      uses: synopsys-sig/synopsys-action@v1.13.0
      with:
        ### SCANNING: Required fields
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: "SCA,SAST"
          
        ### SCANNING: Optional fields
        polaris_application_name: 'verademoNET'
        polaris_project_name: 'verademoNET'
        project_directory: ${{ vars.PROJECT_DIRECTORY }}
        coverity_config_path: /Users/Config/coverity.yml
          
        ### PULL REQUEST COMMENTS: Uncomment below to enable
        polaris_prComment_enabled: true 
        github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

        ### SARIF report parameters
        polaris_reports_sarif_create: true
        polaris_upload_sarif_report: true
          
        ### Signature scan
        polaris_test_sca_type: "SCA-SIGNATURE"
