# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Polaris  
      uses: synopsys-sig/synopsys-action@v1.13.0
      with:
        ### SCANNING: Required fields
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: "SCA,SAST"
          
        ### SCANNING: Optional fields
        polaris_application_name: 'verademoNET'
        polaris_project_name: 'verademoNET'

        ### Uncomment below configuration for source code upload 
        polaris_assessment_mode: "SOURCE_UPLOAD"
        project_source_archive: ${{ github.workspace }}\Verademo-Dotnet
        project_source_excludes: ${{ vars.PROJECT_SOURCE_EXCLUDES }} # Accepts Multiple Values
        project_source_preserveSymLinks: true

        # Mandatory when polaris_prComment_enabled is set to 'true'
        ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
        # include_diagnostics: true
